name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: |
        cd src
        cd NetCore2Blockly
        dotnet tool restore --add-source https://myget.org/F/natemcmaster/api/v3/index.json
        dotnet dotnet-project-licenses  -j  -i NetCore2Blockly.sln
        dotnet dotnet-thx
        dotnet dotnet-outdated
    - name: test
      run: echo done
