# Trigger the workflow on milestone events
on: 
  milestone:
    types: [closed]
name: Milestone Closure
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: "true"

    - name: cp files
      uses: docker://decathlon/wiki-page-creator-action:2.0.1
      env:
        MD_FOLDER: temp_release_notes
        GH_PAT: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN  }}
        ACTION_MAIL: autobot@github.com
        ACTION_NAME: wikirobot
        OWNER: ignatandrei
        REPO_NAME: NETCoreBlockly
        SKIP_MD: README.md